# Site settings
title: JMARK<br>NEL
email: josh@joshmarknelson.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmarknel.com" # the base hostname & protocol for your site
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

twitter_username: jmarknel
github_username:  nelsonJM

# Build settings
markdown: kramdown


