# Site settings
title: jmarknel
email: josh@joshmarknelson.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of notes mostly about product design and customer behavior.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmarknel.com" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

paginate: 1

twitter_username: jmarknel
github_username:  nelsonJM

# Build settings
markdown: kramdown
